INSERT INTO T_ROOM_TYPE (ROOM_TYPE_NAME, SHARED) VALUES ('Standard Shared', TRUE);
INSERT INTO T_ROOM_TYPE (ROOM_TYPE_NAME, SHARED) VALUES ('Standard Double', FALSE);

INSERT INTO T_ROOM (ROOM_NAME, ROOM_TYPE_ID, ROOM_STATUS, OCCUPATION, MAXIMUM_OCCUPATION) VALUES ('Room 1', 0, 'FREE', 3, 8);
INSERT INTO T_ROOM (ROOM_NAME, ROOM_TYPE_ID, ROOM_STATUS, OCCUPATION, MAXIMUM_OCCUPATION) VALUES ('Room 2', 1, 'OCCUPIED', 1, 2);
INSERT INTO T_ROOM (ROOM_NAME, ROOM_TYPE_ID, ROOM_STATUS, OCCUPATION, MAXIMUM_OCCUPATION) VALUES ('Room 3', 0, 'UNCLEAN', 0, 6);
INSERT INTO T_ROOM (ROOM_NAME, ROOM_TYPE_ID, ROOM_STATUS, OCCUPATION, MAXIMUM_OCCUPATION) VALUES ('Room 4', 1, 'IN_MAINTENANCE', 0, 2);

INSERT INTO T_GUEST (GUEST_NAME, DOCUMENT_NUMBER, DOCUMENT_TYPE, BIRTH_DATE) VALUES ('John Doe', '123456789', 'OTHER', TO_DATE('01/01/2000', 'DD/MM/YYYY'));

INSERT INTO T_RESERVE (CHECK_IN, CHECK_OUT, ROOM_ID) VALUES (TO_DATE('01/01/2000', 'DD/MM/YYYY'), TO_DATE('02/01/2000', 'DD/MM/YYYY'), 0);

INSERT INTO T_RESERVE_GUEST(RESERVE_ID, GUEST_ID) VALUES (0, 0);